name: "Mykyta S."
position: "Full-Stack Web Developer"
photo: "me.jpg"

contacts:
  location:
    name: "location"
    title: "Gdańsk, Poland"
    link: "geo:54.4290151,18.5850776"

tagline: Results-driven Full-Stack Web Developer with 5 years building high-performance, scalable applications using or based on the PHP, JavaScript, Node.js and SQL technologies. Led optimizations that boosted page load speeds by 30-40% and retention via SOLID/DRY principles and MVC architecture. Eager to innovate in collaborative teams, delivering efficient solutions for your projects.

work_experiences:
  - position: Full-Stack Web Developer
    company:
      name: SDA Company
    description: 
        - Refactored and enhanced scalable modular backend systems, built with DDD approach by using PHP, Laravel and Laravel Blade, integrating PHPUnit for robust unit testing to ensure code reliability in compliance with HIPAA and ISO/IEC Standards and applying OOP, SOLID, DRY, and KISS principles to streamline our workflow, speed up development and enhance security for sensitive data handling. Also used Stripe and NMI payment processing API.
        - Enhanced frontend side with TypeScript (Angular), JavaScript, jQuery, Bootstrap, and SCSS via Laravel Mix, delivering modular user interfaces that improved application responsiveness.
        - Optimized database performance with MySQL and Memcached, while deploying infrastructure on Amazon Web Services (AWS) and Docker containers, reducing deployment times through BitBucket Pipelines, Git Flow technique and Bash Scripts on Linux-based environment.
    from: "2025-01"
    to: "2025-09"
    location: Remote
  - position: Backend Developer
    company:
      name: Preventa
    description:
      - Extended core functionality using microservices architecture, PHP and TypeScript with Node.js, and designing RESTful APIs to enable seamless data exchange between Laravel backend and React frontend, adhering to ICD-11 and ISO Standards for medical compliance.
      - Refactored codebase integrations to resolve backend performance flaws, using Memcached for caching, resulting in 30-40% faster response times than before.
      - Implemented API queries with caching and mockup testing for partnership integrations.
    from: "2024-09"
    to: "2025-01"
    location: Remote
  - position: Full-Stack Web Developer
    company:
      name: Under NDA
    description:
      - Led optimization of a high-traffic PHP application handling 10+ million media files with ~1.5k online users.
      - Reduced load times on some pages by 50% through reworked MVC architecture and implementing advanced OOP techniques.
      - Developed scalable features utilizing SOLID, DRY, KISS principles, using JavaScript, jQuery, Bootstrap for frontend, and PHP, MySQL+Percona and Memcached for backend, while automating media processing via CRON, FFMPEG, and CDN for efficient high-load operations.
    from: "2022-11"
    to: "2024-09"
    location: Remote
  - position: Full-Stack Web Developer
    company:
      name: Webstick
    description:
      - Played a key role in developing and deploying multiple high-quality web applications, resulting in increase in client satisfaction scores
      - Leveraged Laravel and Yii2 frameworks to build robust backend systems, improving system reliability
      - Implemented modern JavaScript practices with Vue, enhancing the user interface and experience
      - Managed version control through Git and Subversion (SVN), leading improvement in codebase consistency and project collaboration
      - Streamlined the development process by using Open Server, reducing testing time and improving overall development efficiency
    from: "2020-08"
    to: "2022-11"
    location: Kryvyi Rih, Ukraine

education:
  - institution: " State University of Economics and Technology"
    location: "Kryvyi Rih, Ukraine"
    degree: "Master of Science (M.Sc.)"
    field_of_study: "Software Engineering"
    start_date: "2020"
    end_date: "2021"
  - institution: "Kryvyi Rih Economical Institute based on Kyiv National Economic University of Vadym Hetman"
    location: "Kryvyi Rih, Ukraine"
    degree: "Bachelor of Science (B.Sc.)"
    field_of_study: "Software Engineering"
    start_date: "2016"
    end_date: "2020"

skills:
  - PHP
  - JavaScript
  - TypeScript
  - MySQL
  - Node.js
  - Laravel
  - Yii
  - Angular
  - Vue.js
  - React
  - Percona
  - Amazon Web Services (AWS)
  - Docker
  - Git
  - Subversion (SVN)
  - CMake
  - HTML/CSS
  - SASS
  - SCSS
  - Bootstrap
  - jQuery
  - Jenkins
  - GitHub Actions
  - BitBucket Pipelines
  - BugSnag
  - PHPUnit
  - Python
  - WordPress
  - Java
  - OpenAI API
  - Stripe
  - Image-gen AI models (Stable Diffusion, Flux.1)

certifications:
  - name: "ESOL International (Communicator B2)"
    description: Listening, Reading, Writing
